resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
        value: "dev.realstate-scrapper.fullstack.pw"
      - op: replace
        path: /spec/tls/0/hosts/0
        value: "dev.realstate-scrapper.fullstack.pw"
      - op: replace
        path: /spec/rules/0/host
        value: "dev.realstate-scrapper.fullstack.pw"
    target:
      kind: Ingress
      name: realstate-scrapper
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: "dev"
    target:
      kind: Deployment
      name: realstate-scrapper
  - patch: |-
      - op: replace
        path: /spec/strategy
        value:
          type: RollingUpdate
          rollingUpdate:
            maxSurge: 100%
            maxUnavailable: 50%
    target:
      kind: Deployment
      name: realstate-scrapper