apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: memorizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memorizer
  template:
    metadata:
      labels:
        app: memorizer
    spec:
      containers:
        - name: memorizer
          image: registry.fullstack.pw/library/memorizer:latest
          ports:
            - containerPort: 8080
          env:
            - name: ENV
              value: "env"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: opentelemetry-collector.observability.svc.cluster.local:4317
            - name: QUEUE_NAMES
              value: "test-queue"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cluster-secrets
                  key: REDIS_PASSWORD
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
  strategy:
    blueGreen:
      activeService: memorizer
      previewService: memorizer-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 30
