apiVersion: apps/v1
kind: Deployment
metadata:
  name: enqueuer
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: enqueuer
          env:
            - name: ENV
              value: "dev"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enqueuer
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "dev.enqueuer.fullstack.pw"
spec:
  tls:
    - hosts:
        - "dev.enqueuer.fullstack.pw"
      secretName: enqueuer-tls
  rules:
    - host: dev.enqueuer.fullstack.pw
