apiVersion: apps/v1
kind: Deployment
metadata:
  name: trace-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trace-demo
  template:
    metadata:
      labels:
        app: trace-demo
    spec:
      containers:
        - name: trace-demo
          image: registry.fullstack.pw/trace-demo:latest
          ports:
            - containerPort: 8080
          env:
            - name: ENV
              value: env
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: opentelemetry-collector.observability.svc.cluster.local:4317
            - name: DB_HOST
              value: postgres.fullstack.pw
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: postgres
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cluster-secrets
                  key: POSTGRES_PASSWORD
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
