apiVersion: batch/v1
kind: CronJob
metadata:
  name: trace-demo-load
  namespace: default
spec:
  schedule: "*/5 * * * *"  # Run every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: load-generator
            image: busybox
            command:
            - /bin/sh
            - -c
            - |
              for i in $(seq 1 30); do
                wget -q -O- http://trace-demo.default.svc.cluster.local/
                sleep 2
              done
          restartPolicy: OnFailure