apiVersion: apps/v1
kind: Deployment
metadata:
  name: trace-demo
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: trace-demo
          env:
            - name: ENV
              value: "prod"
            - name: DB_NAME
              value: trace-demo-dev

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trace-demo
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "trace-demo.fullstack.pw"
spec:
  tls:
    - hosts:
        - "trace-demo.fullstack.pw"
      secretName: trace-demo-tls
  rules:
    - host: trace-demo.fullstack.pw
